### ISSUE TITLE
Design Principles and Goals 

### ISSUE THREAD

**Issue by BrandonKMLee** [Clay-Ferguson/quantizr#12]
Regarding the design, take a look at https://www.gwern.net/docs/technology/2005-shirky-agroupisitsownworstenemy.pdf
1. handles the user can invest in (the best reputation system is memory)
2. a way for there to be members in good standing, which good works get recognized ("karma system", "name + member since")
3. barriers to participation (named peoples have more ways to display their power)
4. find a way to spare the group from scaling (allow for the divergence and flexibility of community)

If there is an extreme case of such designs, it is an excerpt from Gray Mirror:
1. A powerful app is distinctive. You cannot just decide that you are a member. You have to apply. And once you’re in, you have to keep interacting.
2. A powerful app is organized. All your contents are through and for the app. You share your creativity, and derive consensus, within the app.
3. A powerful app is pseudonymous. Members should be as safe as possible from meatspace consequences of their in-app life.
4. The app is your main info hub. It stockpiles your library with a complete set of world-building designs and creative ideas.
5. The app is your main social hub. It will organize you into localized friend groups. It also gives you local as well as global news. 
6. The app is an important creative asset. If you need a voice actor, writer, or designer, it is always best to talk to your friends in the app. 
7. Besides chatting, the app can coordinate all kinds of friendly community events. An app can notify you of what to bring and what to do.

In essence, the best platform is one that can allow you to:
- Forkable, mergeable, voting based wikis (Gitless? Version Control? WikiJS?)
  - Clear versioning and forking of wiki pages
  - Easy mirroring and archiving of wiki information
  - Well defined ways of voting, deriving consensus, and conflict resolution
- Bipolar-tolerant and divergence-based communities, in better forms than Reddit, Imageboards, and Discord
  - Peaceful mitosis of communities
  - Multiple memberships on the same user
  - Credibility maintenance of users post-split
  - Easy cross-posting and archiving of threads or posts
- Vote-bomb and Sage tolerant design to prevent subcultural conflicts
  - Vouch and referral mechanism?
  - Members-only credibility and seniority-based credibility?
  - Voting spam restrictions and brigading speedbumps?
- Blogs and Galleries that are easily sharable, manageable, and archivable (IPFS? Danbooru?)
  - Easy to use sharing and archiving APIs
  - Community media tagging
  - Cross-referencing and indexing supporting
- An easy-to-handle moderation system when it comes to overlapping communities

**Comment by Clay-Ferguson** [comment]
Those are great ideas, thanks for posting that. With these types of "General Purpose Collaboration" platforms (like Quanta) the sky's the limit, and Quanta is already a solid base to build on.

**Comment by BrandonKMLee** [comment]
@Clay-Ferguson I am thinking in the sense of:
- social necessity factors (bullet points)
- medium of information exchange factors (Wiki vs Blog vs Reddit vs Messaging)
- comparative website feature factors

Not to say this is definitive, but it is kinda important to think about. WYSIWYG?

**Comment by Clay-Ferguson** [comment]
Are you a developer working on similar platforms or just someone sharing some good ideas (which I do appreciate) ?

**Comment by BrandonKMLee** [comment]
I have dreamt of development, an IT major, but have no enough experience to pull off something basic.
But when it comes to the "human" fields I do happen to read a lot bout "the perfect social media".

**Comment by BrandonKMLee** [comment]
With Another day of reading about Uberfact and Revipedia, I found a few more guidelines for a more decentralized Social Media.
Think Reddit and Wikipedia get rolled into one app, but:
- Every Subreddit gets their own Wiki to moderate
- Karma is only self-contained within each subreddit
- Cross-referencing Wiki info from multiple Subreddit is possible
- Version Control and Mirroring is completely transparent

Ultimate goal: Limit edit wars through collective aggregation

**Comment by BrandonKMLee** [comment]
@Clay-Ferguson I could give a few pointers and issues about this idea:
- If Karma is community-specific (i.e. non-fungible and identity specific), how does one create a multi-community feed?
- When communities are having mitosis, how does one handle the transfer of Karma? Like how BCH split away from BTC?
- How does one handle the namespace matching of Wikis if they are heavily diverging in naming schemes? How would alias and disambiguation work?
- What is the best version control system that allows for both moderation and community contribution, without mass edit wars, and allowing for collaborative submissions?
- What is the standard syntax of the Wiki? Would it be like WIki JS? https://js.wiki/
- How does one stop the tactic of Karma bot farming? Introducing a time limit? Or checking the diversity of user upvotes? **Reputation Systems are a good read**

**Comment by Clay-Ferguson** [comment]
Those are some really good things to consider. Thanks for the input!
