### ISSUE TITLE
Issue with page width

### ISSUE THREAD

**Issue by ghost** [Clay-Ferguson/quantizr#20]
So, the max-width for the right column is 33 and a third percent, but on my screen that leaves a lot of empty space on the right side:

![quanta](https://user-images.githubusercontent.com/84287166/118407891-71518300-b648-11eb-98cb-8a3f279c4137.png)

And if I increase my font size, as I often do because my eyes are bad, the same amount of empty space remains:

![quanta2](https://user-images.githubusercontent.com/84287166/118407927-9b0aaa00-b648-11eb-893f-1453ece2ba5b.png)

I'm not sure what would fix the issue, since all the CSS I know I learned by stealing from StackExchange and W3Schools. But it bugs me so I wanted to let you know.

**Comment by Clay-Ferguson** [comment]
Thanks for the feedback. Most people like a narrow view of text, for easier reading. Quanta is actually wider than Mastodon and other apps. That space on the right actually does get used when you upload avatar images (user profile) and looks nicer then. However I was still thinking of adding an option for users to make the content view wider (as an optional setting). It's just using standard bootstrap columns, so I can make it wider by changing a single number in the code, and it will all work/flow just fine.

**Comment by xander-page** [comment]
Thanks for the response! I definitely wouldn't want to ruin it for people who like it that way, so an optional setting would be perfect.

**Comment by Locrian-Zone** [comment]
Thanks for the response! I definitely wouldn't want to ruin it for people who like it that way, so an optional setting would be perfect.

(Responded with the wrong account at first... After going out of my way to make this one specifically for issues regarding Fediverse stuff. Go me.)
